/*
 * Generated by XDoclet - Do not edit!
 */
package com.bln.framework.ejb.sjsb;

import com.bln.framework.transaction.db.ITransaction;

/**
 * Local interface for TransHandler.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TransHandlerLocal
   extends javax.ejb.EJBLocalObject, ITransaction
{

}
