/*
 * Generated by XDoclet - Do not edit!
 */
package com.bln.framework.ejb.sjsb;

import java.rmi.RemoteException;

import com.bln.framework.biz.service.IService;
import com.bln.framework.mo.IMessageObject;

/**
 * Remote interface for TransHandler.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TransHandler extends javax.ejb.EJBObject
{
	/**
	 * 启动新的事物处理
	 * @param serviceObj 服务对象
	 * @param reqMo 请求消息对象
	 * @return 响应消息对象
	 * @throws Throwable 服务时所抛出的异常
	 */
	public IMessageObject requireNewTrans(IService serviceObj, IMessageObject reqMo) throws Throwable, RemoteException;
	
	//for WAS
	//public IMessageObject requireNewTrans(IService serviceObj, IMessageObject reqMo) throws RemoteException;
	
	/**
	 * 如果当前有事务，添加到当前事务中，否则启动新的事物
	 * @param serviceObj 服务对象
	 * @param reqMo 请求消息对象
	 * @return 响应消息对象
	 * @throws Throwable 服务时所抛出的异常
	 */
	public IMessageObject requireTrans(IService serviceObj, IMessageObject reqMo) throws Throwable, RemoteException;

	//for WAS
	//public IMessageObject requireTrans(IService serviceObj, IMessageObject reqMo) throws RemoteException;
	
}
