/*
 * Generated by XDoclet - Do not edit!
 */
package com.bln.framework.ejb.sjsb;

/**
 * Local home interface for TransHandler.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TransHandlerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TransHandlerLocal";
   public static final String JNDI_NAME="TransHandlerLocal";

   public com.bln.framework.ejb.sjsb.TransHandlerLocal create()
      throws javax.ejb.CreateException;

}
