/*
 * Generated by XDoclet - Do not edit!
 */
package com.bln.framework.ejb.sjsb;

/**
 * Home interface for TransHandler.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TransHandlerHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TransHandler";
   public static final String JNDI_NAME="ejb/TransHandler";

   public com.bln.framework.ejb.sjsb.TransHandler create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
